### ISSUE TITLE
How do you change settings/options?

### ISSUE THREAD

**Issue by melnation-com** [Snaacky/thewiki#270]
Tried right clicking in the middle of vid, it acts as a pause. I wish to change shortcut for volume, which currently acts as a 1 minute seek, speaking of seek I would also wish to change Seek length. Already checked some sort of config file but none related to shortcuts or Seek length. Thanks.

I heard this was a fork or something, I didn't install anything else but what's here https://github.com/Snaacky/thewiki/releases/

I didn't downloaded/installed [zhongfly's build](https://github.com/zhongfly/mpv-winbuild)

Also, the MPV version is the April 6~7 2024 version(depends on timezone)

**Comment by Ravencentric** [comment]
You can use the [`input.conf`](https://github.com/mpv-player/mpv/blob/master/etc/input.conf) to map any key to anything.

Also, the issues are for issues directly related to thewiki. For support/help, join our discord linked on the readme

**Comment by melnation-com** [comment]
> > I heard this was a fork or something, I didn't install anything else but what's here https://github.com/Snaacky/thewiki/releases/
> 
> > I didn't downloaded/installed [zhongfly's build](https://github.com/zhongfly/mpv-winbuild)
> 
> That's not a fork, that's just zhongfly's build with a premade configuration
> 
> You can use the [`input.conf`](https://github.com/mpv-player/mpv/blob/master/etc/input.conf) to map any key to anything.
> 
> Also, the issues are for issues directly related to thewiki. For support/help, join our discord linked on the readme

Can I know how to find the documentation for input.config? currently it only has
"# restyle subtitles by pressing k
k cycle_values sub-ass-override "force" "no"
"

**Comment by Ravencentric** [comment]
I linked it to you right above. These are the defaults: https://github.com/mpv-player/mpv/blob/master/etc/input.conf

Just pick and choose what you want and override them

**Comment by melnation-com** [comment]
Thanks, made some few changes, this is my settings

`# restyle subtitles by pressing k
k cycle_values sub-ass-override "force" "no"
RIGHT seek  5                          # seek 5 seconds forward
LEFT  seek -5                          # seek 5 seconds backward
UP    add volume 2                     # seek 1 minute forward
DOWN  add volume -2                    # seek 1 minute backward
a cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1" # cycle the video aspect ratio ("-1" is the container aspect)
PGUP seek 60                          # seek to the next chapter
PGDWN seek -60                        # seek to the previous chapter

`

**Comment by Ravencentric** [comment]
it's three backticks btw

``````
```
your content
```
``````

**Comment by Ravencentric** [comment]
Anyway, I'm closing this issue considering it's resolved now.
