### ISSUE TITLE
Add more comps

### ISSUE THREAD

**Issue by Ravencentric** [Snaacky/thewiki#85]
Add these:
https://slow.pics/c/vpcExtLb
https://slow.pics/c/HZeCzBjs
to:
http://thewiki.moe/guides/quality/#types-of-releases
![image](https://github.com/Snaacky/thewiki/assets/78981416/2367d50d-8232-4ac2-a909-6dad9b3a01e2)

**Comment by ricky8k** [comment]
Added in https://github.com/Snaacky/thewiki/pull/86.
